stages:
   data_preparation:
      cmd: python3 scripts/data_preparation.py
      deps:
         - data/raw/X_train.csv
         - data/raw/X_test.csv
         - data/raw/Y_train.csv
         - data/raw/Y_test.csv
         - scripts/data_preparation.py
      outs:
         - data/prepared/X_train_prepared.csv
         - data/prepared/X_test_prepared.csv
         - data/prepared/Y_train_prepared.csv
         - data/prepared/Y_test_prepared.csv
   model_create_fit:
      cmd: python3 scripts/model_create_fit.py
      deps:
         - data/prepared/X_train_prepared.csv
         - data/prepared/Y_train_prepared.csv
         - scripts/model_create_fit.py
      params:
         - batch_size
         - epochs
         - validation_split
         - verbose
      outs:
         - mnist_simple_model
   model_quality_assessment:
      cmd: python3 scripts/model_quality_assessment.py
      deps:
         - mnist_simple_model
         - data/prepared/X_test_prepared.csv
         - data/prepared/Y_test_prepared.csv
         - scripts/model_quality_assessment.py
      metrics:
         - results.json:
            cache: false
